<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tracking_awbInput</name>
   <tag></tag>
   <elementGuidId>5694d4c9-4383-443e-b712-6e43c5f7cb81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sqpp-tracking-quicksearch-awbfield-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sqpp-tracking-quicksearch-awbfield-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee67787d-a856-4a1e-a1b1-0036faee50d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sqpp-tracking-quicksearch-awbfield-id</value>
      <webElementGuid>14156cc5-1a6a-4f17-b28e-20568c42d71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fa5585a9-c34a-4bf3-a6ea-6db29a58a759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>awbInput</value>
      <webElementGuid>942baea4-0338-4bb0-ab3d-7f4c101f4e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter AWB number separated by a comma. For example, 618-1234XXXX.</value>
      <webElementGuid>6e548805-b2e6-4cbe-9be2-0362793b86eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f740643f-0b80-4147-b14e-bb32cb8fd803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o sqpp-tracking-quicksearch-awbfield form-control</value>
      <webElementGuid>317c53f6-370a-4517-8651-9bb1f00bbf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af1845b6-d1f6-4079-a056-063f62ebbe0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sqpp-tracking-quicksearch-awbfield-id&quot;)</value>
      <webElementGuid>d6e820d8-9ca6-4f7c-abdf-5aa556f2a22d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sqpp-tracking-quicksearch-awbfield-id']</value>
      <webElementGuid>723532fc-e07b-4f09-9074-83d1c648d61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tracking-quicksearch[@id='scquicksearch']/div/div/div/div/input</value>
      <webElementGuid>e136c4e2-29fb-4593-952e-c32099fa2f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tracking-quicksearch/div/div/div/div/input</value>
      <webElementGuid>a5fbe81f-7c1a-48f0-ab3e-4325634c159b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sqpp-tracking-quicksearch-awbfield-id' and @name = 'awbInput' and @placeholder = 'Enter AWB number separated by a comma. For example, 618-1234XXXX.' and @type = 'text']</value>
      <webElementGuid>b8079411-f4d1-49ab-bc30-a0126dc93296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
