<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SEARCH</name>
   <tag></tag>
   <elementGuidId>e22c324a-56ca-43ae-9e57-fcbbb279714c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.theme-module_btn__Dp-TQ.index_sqpp-primary-download-btn__L16Sa.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b985c904-c020-4d1a-95f8-ec1758b535bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2e1d536-51d4-4459-8d9c-b1fd7ca6514d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary</value>
      <webElementGuid>76cc9096-1855-4486-aa2e-a28b86b11200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>4408fb5d-4faf-4c7d-8489-e535734b5d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scflightschedule&quot;)/div[@class=&quot;FS-wrapper-container sqpp-master-container&quot;]/span[1]/div[1]/div[@class=&quot;flightSearch large-screen-size&quot;]/div[@class=&quot;flightSearchContainer&quot;]/div[@class=&quot;flightSearchFilterContainer&quot;]/div[@class=&quot;fsSearchActions&quot;]/span[@class=&quot;index_sqpp-primary-download-btn-container__FaCQe&quot;]/button[@class=&quot;theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary&quot;]</value>
      <webElementGuid>6adf6792-6691-46b9-9c9b-b8665b520550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>bed459f0-9b5b-4b1a-8638-34b6b7733347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div[2]/div[2]/span/button</value>
      <webElementGuid>fbedef59-49c2-4e89-a477-4b5374ca4130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset / New Search'])[1]/preceding::button[1]</value>
      <webElementGuid>457f0ae3-9e76-4080-97b8-84d4cf7081c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need an overview for a flight or route? Download eTimetable'])[1]/preceding::button[1]</value>
      <webElementGuid>aaace16a-b18e-4f60-85d7-aa7adabcad69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>3eb0b2e7-c8ab-49b4-b309-182146993306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>e5d6f8b5-5579-4c8d-abaf-e7a2c7646987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>86b50915-f482-4367-b1f7-4f8c51bd748f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
