<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination_fromFlightDate</name>
   <tag></tag>
   <elementGuidId>980a59f8-129c-4419-ac24-983aeef55666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromFlightDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromFlightDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f04e91c-5075-4741-9539-e02ad4a0c6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>043e4f93-7469-47ef-951c-63a02158210e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromFlightDate</value>
      <webElementGuid>e85fff03-5fab-42de-942f-00c04b1427ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromFlightDate</value>
      <webElementGuid>e12613be-7896-4ae0-8b9a-a80aa9d40fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ad57b1ef-abe9-4f26-8804-1382fa198c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-date </value>
      <webElementGuid>8691a879-cf1f-4b75-b6a8-62b9569c129c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromFlightDate&quot;)</value>
      <webElementGuid>cc0e2b22-d8bb-4c35-9ca3-61b62baaf14f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromFlightDate']</value>
      <webElementGuid>ae74b63c-42dd-4d8a-95f3-a4db46e39dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>1107f571-7d5f-473b-80d3-cb6c9a62da53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>eac1cd8f-8873-416b-9a81-730765c5738e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fromFlightDate' and @name = 'fromFlightDate']</value>
      <webElementGuid>fdcc643d-0b0b-4b8d-afd5-bd1ae9cf2a3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
