<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flight Schedule_origin</name>
   <tag></tag>
   <elementGuidId>6c3f6513-5f79-4858-8ee3-c29381c663a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#origin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='origin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a939f43-4a95-4426-aabc-cb3a4f84009b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1dffd124-839f-40f3-ae1d-c0892039b38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49f8bcec-8059-4c6d-bd64-f7df6c2d695e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control index_sqpp-odpair-autocomplete-input__XaMRT mx-1&quot; 
                </value>
      <webElementGuid>b4d2678f-2010-47e1-b38c-47fcb0c6ae98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>6c1d4a3a-f279-49c5-ba50-1ea886ba0af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>f7ea6da8-e895-4b56-96d4-0793a9fc7747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>b3eb09f0-08ba-41ba-a272-c4fc82344f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;origin&quot;)</value>
      <webElementGuid>68ff5c7d-4d49-41f5-ab67-510b34b53998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='origin']</value>
      <webElementGuid>d4e18897-ccfb-4013-b4d1-77f89aef8cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>adb2bdc2-73bb-4ab8-ad1c-72a0ac903fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>6a23323c-3717-4108-96e5-c3c4c2ea9171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Origin' and @name = 'origin' and @id = 'origin']</value>
      <webElementGuid>5f811036-1414-458f-b0c2-15b47306ef23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
