<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination_fromFlightDate</name>
   <tag></tag>
   <elementGuidId>980a59f8-129c-4419-ac24-983aeef55666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromFlightDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromFlightDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f571e493-553d-4dd2-963c-99bde4144597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55f3e9c8-ee00-4b9f-a2ad-c7896ba9237e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromFlightDate</value>
      <webElementGuid>7132cd4d-9922-4d45-803c-9ab3e8baf89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromFlightDate</value>
      <webElementGuid>09075082-5a5c-47f3-ae5b-1e8bccad16ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>32dfeac0-6ffd-4e05-a951-39822d0b5a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-date </value>
      <webElementGuid>172eaa30-c50e-421b-a067-31808103f943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromFlightDate&quot;)</value>
      <webElementGuid>e1993f7a-c8f0-483b-b476-c845467a138d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromFlightDate']</value>
      <webElementGuid>57834c78-4f2b-4fb2-abac-7219f41bd161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>3f234f86-9294-43f4-8025-b224c0ab41a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>97ac2c53-14e8-4d6e-9a08-b8c4a5c16134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fromFlightDate' and @name = 'fromFlightDate']</value>
      <webElementGuid>1c9280c1-63d2-435f-8717-6b9e4a3dd63b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
