<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flight Schedule_origin</name>
   <tag></tag>
   <elementGuidId>6c3f6513-5f79-4858-8ee3-c29381c663a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#origin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='origin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af7f0178-54e1-4b18-9cc6-3bdfe0aab6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6e20f84c-cc29-46c1-b661-4dc93e7e8fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89cec85f-3065-424b-b674-ae75c5ee9af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control index_sqpp-odpair-autocomplete-input__XaMRT mx-1&quot; 
                </value>
      <webElementGuid>83271a5d-c5f9-49a4-a903-4aedbb42c059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>44f32137-2942-4daf-b4da-2cd173e6a57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>4077476e-abda-47ed-b110-c59aba9944a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>86790a4e-b8b1-4f09-84dc-473967eda97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;origin&quot;)</value>
      <webElementGuid>724de0ab-4a1c-47c1-8ee0-e1eb43bf0d4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='origin']</value>
      <webElementGuid>0ed406c9-7df2-4988-ae5e-f6b8e2aa5121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ea915dad-665e-4b5c-9a1d-83c0c0130a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>6b7321fa-d47c-487e-b309-ed7d44a84978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Origin' and @name = 'origin' and @id = 'origin']</value>
      <webElementGuid>6a238b33-9694-40da-95bd-0d56bef43a5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
