<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reset  New Search</name>
   <tag></tag>
   <elementGuidId>b3c84e2e-8c4b-4f1d-8d79-5cb5f5db504e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fsResetSearchButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div[2]/div[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00fc05a9-2572-4cd2-a788-64a7f3b20543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fsResetSearchButton</value>
      <webElementGuid>4447c9de-33da-4483-931e-30e9dd730add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset / New Search</value>
      <webElementGuid>67ec56c7-1f6c-4fe4-9b5c-3ab1d80ac76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scflightschedule&quot;)/div[@class=&quot;FS-wrapper-container sqpp-master-container&quot;]/span[1]/div[1]/div[@class=&quot;flightSearch large-screen-size&quot;]/div[@class=&quot;flightSearchContainer&quot;]/div[@class=&quot;flightSearchFilterContainer&quot;]/div[@class=&quot;fsSearchActions&quot;]/span[@class=&quot;fsResetSearchButton&quot;]</value>
      <webElementGuid>0782a6c9-aaf6-4e6d-8fc9-846d606ac4dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div[2]/div[2]/span[2]</value>
      <webElementGuid>8cceb88a-a133-4eeb-9a2e-2d3342a4d36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH'])[1]/following::span[1]</value>
      <webElementGuid>304d998e-6094-4bb8-baf8-aac3916b64d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SORT BY'])[1]/preceding::span[1]</value>
      <webElementGuid>8a26fd2e-cdd2-4016-b07d-00dc3f271dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departure Time'])[1]/preceding::span[1]</value>
      <webElementGuid>5f01d892-f33e-46e0-aeba-387b59455756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset / New Search']/parent::*</value>
      <webElementGuid>5276f0b5-c843-4591-90ba-6caa79b1359e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>a1a6039b-43a8-4b3c-99ab-846fec87753d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Reset / New Search' or . = 'Reset / New Search')]</value>
      <webElementGuid>1104cc17-7ecc-4da4-8560-1f13d1318acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
