<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10</name>
   <tag></tag>
   <elementGuidId>00adaf1f-18c4-4de1-b3a6-db1f7c376242</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.FS-Pagination-total-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flight-schedule[@id='scflightschedule']/div/span/div[2]/div/div[2]/div/table/tbody/tr[11]/td/span/div/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d92bf47-4dde-41e1-8694-8ba35fa4f42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FS-Pagination-total-results</value>
      <webElementGuid>48f9e560-0e6b-4e1f-909a-9ba35d90b85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>902ceebb-9836-47f7-a705-976fbad33a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scflightschedule&quot;)/div[@class=&quot;FS-wrapper-container sqpp-master-container&quot;]/span[1]/div[2]/div[@class=&quot;FlightScheduleResultContainer&quot;]/div[@class=&quot;FlightScheduleResultTableContainer&quot;]/div[@class=&quot;FlightScheduleResultHeaderTable&quot;]/table[@class=&quot;FlightScheduleResultTable&quot;]/tbody[1]/tr[11]/td[@class=&quot;FS-PaginationContainer&quot;]/span[@class=&quot;FS-Pagination&quot;]/div[@class=&quot;FS-Pagination-actions&quot;]/span[@class=&quot;FS-Pagination-results-count&quot;]/span[@class=&quot;FS-Pagination-total-results&quot;]</value>
      <webElementGuid>ef208128-23fb-47e8-b44a-d466fdaab880</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div[2]/div/div[2]/div/table/tbody/tr[11]/td/span/div/span/span[2]</value>
      <webElementGuid>a4bff4d0-6b9a-4e7c-aa88-d2c8db165d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing:'])[1]/following::span[1]</value>
      <webElementGuid>ee190406-8845-43a9-8b10-43c16efa9dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[18]/following::span[4]</value>
      <webElementGuid>7a8f8b0f-b9b5-4c0d-9cf7-e8f9efe9ef97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIA Cargo Office'])[1]/preceding::span[4]</value>
      <webElementGuid>298de101-84da-49e8-8209-2b716286ce29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span/span[2]</value>
      <webElementGuid>a9fb8a0b-70af-4f36-971a-41ec00ce7215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '10' or . = '10')]</value>
      <webElementGuid>9ce68d1c-d000-4c3f-9731-8bf4cc340ff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
