<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SQ0211</name>
   <tag></tag>
   <elementGuidId>dd106477-b0e8-4bf8-a3d2-7ebced58709b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flight-schedule[@id='scflightschedule']/div/span/div[2]/div/div[2]/div/table/tbody/tr[7]/td/table/tbody/tr[2]/td[2]/div/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05d8ae94-9b04-4cea-9435-47ff17932609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SQ0211</value>
      <webElementGuid>4394972a-a5fb-4b51-8d29-97002bf0a703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scflightschedule&quot;)/div[@class=&quot;FS-wrapper-container sqpp-master-container&quot;]/span[1]/div[2]/div[@class=&quot;FlightScheduleResultContainer&quot;]/div[@class=&quot;FlightScheduleResultTableContainer&quot;]/div[@class=&quot;FlightScheduleResultHeaderTable&quot;]/table[@class=&quot;FlightScheduleResultTable&quot;]/tbody[1]/tr[@class=&quot;FlightScheduleResultInfo&quot;]/td[1]/table[1]/tbody[1]/tr[@class=&quot;FlightScheduleDetails&quot;]/td[2]/div[@class=&quot;FlightScheduleAircraftTypeDetailsContainer&quot;]/span[@class=&quot;FlightScheduleAircraftTypeDetails&quot;]/span[1]</value>
      <webElementGuid>7be6dacb-6e4a-4a12-9f6c-9ab4a776a817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div[2]/div/div[2]/div/table/tbody/tr[7]/td/table/tbody/tr[2]/td[2]/div/span[2]/span</value>
      <webElementGuid>b5c6a6fb-3a5b-4d7b-9457-3e8b4b1c56ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sydney'])[8]/following::span[4]</value>
      <webElementGuid>6fe94f02-40a9-4b4b-a207-124de1495e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[8]/following::span[8]</value>
      <webElementGuid>08fcc156-d172-4241-9f95-dd6fc858a993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boeing 777-300ER'])[3]/preceding::span[1]</value>
      <webElementGuid>a3772074-86cc-4ec8-8f11-7f3c3429d75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wide Body'])[6]/preceding::span[2]</value>
      <webElementGuid>9c63ce62-1eed-49f8-adac-3eca11668c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/table/tbody/tr[2]/td[2]/div/span[2]/span</value>
      <webElementGuid>95b5b7b7-d411-4b5f-93c6-73b3bdc93b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SQ0211' or . = 'SQ0211')]</value>
      <webElementGuid>c5f74473-f101-47f9-8dee-8caba45f7dc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
