<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tracking</name>
   <tag></tag>
   <elementGuidId>2fa01614-2085-47a4-a18f-edc999247f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2123 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2123']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b003de8c-40c2-4678-b252-31803f5763e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.siacargo.com/e-services/quicksearch_public/</value>
      <webElementGuid>20614c6e-2b90-4e36-813d-46f32aa7e2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tracking</value>
      <webElementGuid>63ffe433-aeda-4d74-9b2f-fe601d6fd014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2123&quot;)/a[1]</value>
      <webElementGuid>26614945-3487-41e8-bd27-e84bb0df69e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2123']/a</value>
      <webElementGuid>a05caecd-6eb3-4da8-a7fc-ea4ab1c69eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tracking')]</value>
      <webElementGuid>abf53538-957c-4729-ad9d-c7571c2d81ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Schedule'])[1]/following::a[1]</value>
      <webElementGuid>f9e0611a-02e3-4016-aa6b-318f32275328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valuable Cargo'])[1]/following::a[3]</value>
      <webElementGuid>e00ecf63-4fa5-40ea-96c4-e63efabec81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eTimetable'])[1]/preceding::a[1]</value>
      <webElementGuid>1b258a23-af5b-4c89-bb67-a68ee69918df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eAWB'])[1]/preceding::a[2]</value>
      <webElementGuid>87625704-eec4-44fe-809a-e1fcde38cb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tracking']/parent::*</value>
      <webElementGuid>3ccd98b5-ad06-4d56-b576-ecb15136cc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.siacargo.com/e-services/quicksearch_public/')]</value>
      <webElementGuid>d13e1e20-a76b-4d5b-bc41-e395ddb91d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>b1961dca-861e-460e-8fdf-96ab3bfa3a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.siacargo.com/e-services/quicksearch_public/' and (text() = 'Tracking' or . = 'Tracking')]</value>
      <webElementGuid>4740a352-ed4b-4010-b987-b5772b6b715e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
